package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	QUORUM_REQUEST, QUORUM_RESPONSE,
	FRIEND_REQUEST, FRIEND_ACCEPT,
	REMOVE_FILE,
	VIEW_FILES, VIEW_FILES_TELL
}
