package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	QUORUM_REQUEST, QUORUM_RESPONSE,
	FRIEND_REQUEST, FRIEND_ACCEPT,
	REMOVE_FILE, REMOVE_FILE_CREATOR,
	VIEW_FILES, VIEW_FILES_TELL,
	PING, PONG, ALIVE,
	REMOVE_NODE,
	BACK_UP, SEARCH_FOR_BACK_UP, BACK_UP_FOUND_TELL
}
